[profile.release]
lto = true
codegen-units = 1

[workspace]
resolver = "2"
members = ["bench", "sdk", "server" ]

[workspace.metadata.cargo-machete]
ignored = ["openssl"]


[workspace.dependencies]
rkyv = "0.8.9"