[profile.release]
lto = true
codegen-units = 1

[workspace]
resolver = "2"
members = ["bench", "bench/report", "sdk", "server" ]

[workspace.metadata.cargo-machete]
ignored = ["openssl"]


[workspace.dependencies]
rkyv = { version = "0.8.9" , features = ["unaligned"] }