apiVersion: v1
kind: Service
metadata:
  name: {{ include "iggy.fullname" . }}
  labels:
    {{- include "iggy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.tcpPort }}
      targetPort: tcp
      protocol: TCP
      name: tcp
    - port: {{ .Values.service.quicPort }}
      targetPort: quic
      protocol: UDP
      name: quic
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "iggy.selectorLabels" . | nindent 4 }}
